name: word
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.1
  get_it: ^7.6.7
  sized_context: ^1.0.0+4
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  desktop_window: ^0.4.0
  flutter_displaymode: ^0.6.0
  intl: ^0.19.0
  get_it_mixin: ^4.2.2
  flex_color_scheme: ^7.3.1
  responsive_framework: ^1.4.0
  extra_alignments: ^1.0.0+1
  animations: ^2.0.11
  flutter_hooks: ^0.20.5
  dynamic_color: ^1.7.0
  gap: ^3.0.1
  material_symbols_icons: ^4.2719.3
  animated_text_kit: ^4.2.2
  flextras: ^1.0.0
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/tabs/
    - assets/settings/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

